export const portfolio = [
  {
    name: "Bridal",
    main: "/portfolioBridal.png",
    other: [
      "/portfolioBridal.png",
      "/portfolioBridal.png",
      "/portfolioBridal.png",
      "/portfolioBridal.png",
      "/portfolioBridal.png",
      "/portfolioBridal.png",
      "/portfolioBridal.png",
    ],
  },
  {
    name: "Traditional bridal",
    main: "/portfolioTrad.png",
    other: [
      "/portfolioTrad.png",
      "/portfolioTrad.png",
      "/portfolioTrad.png",
      "/portfolioTrad.png",
      "/portfolioTrad.png",
      "/portfolioTrad.png",
      "/portfolioTrad.png",
      "/portfolioTrad.png",
      "/portfolioTrad.png",
    ],
  },
  {
    name: "Bridal train",
    main: "/portfolioTrain.png",
    other: [
      "/portfolioTrain.png",
      "/portfolioTrain.png",
      "/portfolioTrain.png",
      "/portfolioTrain.png",
      "/portfolioTrain.png",
      "/portfolioTrain.png",
      "/portfolioTrain.png",
    ],
  },
  {
    name: "Wedding Guest",
    main: "/portfolioGuest.png",
    other: [
      "/portfolioGuest.png",
      "/portfolioGuest.png",
      "/portfolioGuest.png",
      "/portfolioGuest.png",
      "/portfolioGuest.png",
      "/portfolioGuest.png",
    ],
  },
  {
    name: " Non Tradition",
    main: "/portfolioNontrad.png",
    other: [
      "/portfolioNontrad.png",
      "/portfolioNontrad.png",
      "/portfolioNontrad.png",
      "/portfolioNontrad.png",
      "/portfolioNontrad.png",
      "/portfolioNontrad.png",
      "/portfolioNontrad.png",
      "/portfolioNontrad.png",
    ],
  },
];
